alias: Satisfactory-Circutriy-Alexa
description: ""
trigger:
  - platform: webhook
    allowed_methods:
      - GET
    local_only: true
    webhook_id: Satisfactory-Circutriy-Alexa-38e188459fe8
condition: []
action:
  - service: shell_command.update_alert_json
    data:
      query: "@'{{ trigger.query.items() }}'"
  - service: media_player.play_media
    target:
      entity_id: media_player.buro_show
    data:
      media_content_id: amzn1.ask.skill.9cd2a402-4860-4aca-a30d-43d7df5ee351
      media_content_type: skill
